import { Country } from '../entities/county.entity';

export const countrySeedData: Array<Country> = [
  { id: 'AF', name: 'Afghanistan', shortName: 'AFG', countryCode: '+93' },
  { id: 'AL', name: 'Albania', shortName: 'ALB', countryCode: '+355' },
  { id: 'DZ', name: 'Algeria', shortName: 'DZA', countryCode: '+213' },
  { id: 'AD', name: 'Andorra', shortName: 'AND', countryCode: '+376' },
  { id: 'AO', name: 'Angola', shortName: 'AGO', countryCode: '+244' },
  { id: 'AR', name: 'Argentina', shortName: 'ARG', countryCode: '+54' },
  { id: 'AM', name: 'Armenia', shortName: 'ARM', countryCode: '+374' },
  { id: 'AU', name: 'Australia', shortName: 'AUS', countryCode: '+61' },
  { id: 'AT', name: 'Austria', shortName: 'AUT', countryCode: '+43' },
  { id: 'AZ', name: 'Azerbaijan', shortName: 'AZE', countryCode: '+994' },
  { id: 'BS', name: 'Bahamas', shortName: 'BHS', countryCode: '+1-242' },
  { id: 'BH', name: 'Bahrain', shortName: 'BHR', countryCode: '+973' },
  { id: 'BD', name: 'Bangladesh', shortName: 'BGD', countryCode: '+880' },
  { id: 'BB', name: 'Barbados', shortName: 'BRB', countryCode: '+1-246' },
  { id: 'BY', name: 'Belarus', shortName: 'BLR', countryCode: '+375' },
  { id: 'BE', name: 'Belgium', shortName: 'BEL', countryCode: '+32' },
  { id: 'BZ', name: 'Belize', shortName: 'BLZ', countryCode: '+501' },
  { id: 'BJ', name: 'Benin', shortName: 'BEN', countryCode: '+229' },
  { id: 'BT', name: 'Bhutan', shortName: 'BTN', countryCode: '+975' },
  { id: 'BO', name: 'Bolivia', shortName: 'BOL', countryCode: '+591' },
  {
    id: 'BA',
    name: 'Bosnia and Herzegovina',
    shortName: 'BIH',
    countryCode: '+387',
  },
  { id: 'BW', name: 'Botswana', shortName: 'BWA', countryCode: '+267' },
  { id: 'BR', name: 'Brazil', shortName: 'BRA', countryCode: '+55' },
  { id: 'BN', name: 'Brunei', shortName: 'BRN', countryCode: '+673' },
  { id: 'BG', name: 'Bulgaria', shortName: 'BGR', countryCode: '+359' },
  { id: 'BF', name: 'Burkina Faso', shortName: 'BFA', countryCode: '+226' },
  { id: 'BI', name: 'Burundi', shortName: 'BDI', countryCode: '+257' },
  { id: 'KH', name: 'Cambodia', shortName: 'KHM', countryCode: '+855' },
  { id: 'CM', name: 'Cameroon', shortName: 'CMR', countryCode: '+237' },
  { id: 'CA', name: 'Canada', shortName: 'CAN', countryCode: '+1' },
  { id: 'CV', name: 'Cape Verde', shortName: 'CPV', countryCode: '+238' },
  {
    id: 'CF',
    name: 'Central African Republic',
    shortName: 'CAF',
    countryCode: '+236',
  },
  { id: 'TD', name: 'Chad', shortName: 'TCD', countryCode: '+235' },
  { id: 'CL', name: 'Chile', shortName: 'CHL', countryCode: '+56' },
  { id: 'CN', name: 'China', shortName: 'CHN', countryCode: '+86' },
  { id: 'CO', name: 'Colombia', shortName: 'COL', countryCode: '+57' },
  { id: 'KM', name: 'Comoros', shortName: 'COM', countryCode: '+269' },
  {
    id: 'CG',
    name: 'Congo (Congo-Brazzaville)',
    shortName: 'COG',
    countryCode: '+242',
  },
  {
    id: 'CD',
    name: 'Congo (Congo-Kinshasa)',
    shortName: 'COD',
    countryCode: '+243',
  },
  { id: 'CR', name: 'Costa Rica', shortName: 'CRI', countryCode: '+506' },
  { id: 'HR', name: 'Croatia', shortName: 'HRV', countryCode: '+385' },
  { id: 'CU', name: 'Cuba', shortName: 'CUB', countryCode: '+53' },
  { id: 'CY', name: 'Cyprus', shortName: 'CYP', countryCode: '+357' },
  {
    id: 'CZ',
    name: 'Czechia (Czech Republic)',
    shortName: 'CZE',
    countryCode: '+420',
  },
  { id: 'DK', name: 'Denmark', shortName: 'DNK', countryCode: '+45' },
  { id: 'DJ', name: 'Djibouti', shortName: 'DJI', countryCode: '+253' },
  { id: 'DM', name: 'Dominica', shortName: 'DMA', countryCode: '+1-767' },
  {
    id: 'DO',
    name: 'Dominican Republic',
    shortName: 'DOM',
    countryCode: '+1-809, +1-829, +1-849',
  },
  { id: 'EC', name: 'Ecuador', shortName: 'ECU', countryCode: '+593' },
  { id: 'EG', name: 'Egypt', shortName: 'EGY', countryCode: '+20' },
  { id: 'SV', name: 'El Salvador', shortName: 'SLV', countryCode: '+503' },
  {
    id: 'GQ',
    name: 'Equatorial Guinea',
    shortName: 'GNQ',
    countryCode: '+240',
  },
  { id: 'ER', name: 'Eritrea', shortName: 'ERI', countryCode: '+291' },
  { id: 'EE', name: 'Estonia', shortName: 'EST', countryCode: '+372' },
  { id: 'ET', name: 'Ethiopia', shortName: 'ETH', countryCode: '+251' },
  { id: 'FJ', name: 'Fiji', shortName: 'FJI', countryCode: '+679' },
  { id: 'FI', name: 'Finland', shortName: 'FIN', countryCode: '+358' },
  { id: 'FR', name: 'France', shortName: 'FRA', countryCode: '+33' },
  { id: 'GA', name: 'Gabon', shortName: 'GAB', countryCode: '+241' },
  { id: 'GM', name: 'Gambia', shortName: 'GMB', countryCode: '+220' },
  { id: 'GE', name: 'Georgia', shortName: 'GEO', countryCode: '+995' },
  { id: 'DE', name: 'Germany', shortName: 'DEU', countryCode: '+49' },
  { id: 'GH', name: 'Ghana', shortName: 'GHA', countryCode: '+233' },
  { id: 'GR', name: 'Greece', shortName: 'GRC', countryCode: '+30' },
  { id: 'GD', name: 'Grenada', shortName: 'GRD', countryCode: '+1-473' },
  { id: 'GT', name: 'Guatemala', shortName: 'GTM', countryCode: '+502' },
  { id: 'GN', name: 'Guinea', shortName: 'GIN', countryCode: '+224' },
  { id: 'GW', name: 'Guinea-Bissau', shortName: 'GNB', countryCode: '+245' },
  { id: 'GY', name: 'Guyana', shortName: 'GUY', countryCode: '+592' },
  { id: 'HT', name: 'Haiti', shortName: 'HTI', countryCode: '+509' },
  { id: 'HN', name: 'Honduras', shortName: 'HND', countryCode: '+504' },
  { id: 'HU', name: 'Hungary', shortName: 'HUN', countryCode: '+36' },
  { id: 'IS', name: 'Iceland', shortName: 'ISL', countryCode: '+354' },
  { id: 'IN', name: 'India', shortName: 'IND', countryCode: '+91' },
  { id: 'ID', name: 'Indonesia', shortName: 'IDN', countryCode: '+62' },
  { id: 'IR', name: 'Iran', shortName: 'IRN', countryCode: '+98' },
  { id: 'IQ', name: 'Iraq', shortName: 'IRQ', countryCode: '+964' },
  { id: 'IE', name: 'Ireland', shortName: 'IRL', countryCode: '+353' },
  { id: 'IL', name: 'Israel', shortName: 'ISR', countryCode: '+972' },
  { id: 'IT', name: 'Italy', shortName: 'ITA', countryCode: '+39' },
  { id: 'CI', name: 'Ivory Coast', shortName: 'CIV', countryCode: '+225' },
  { id: 'JM', name: 'Jamaica', shortName: 'JAM', countryCode: '+1-876' },
  { id: 'JP', name: 'Japan', shortName: 'JPN', countryCode: '+81' },
  { id: 'JO', name: 'Jordan', shortName: 'JOR', countryCode: '+962' },
  { id: 'KZ', name: 'Kazakhstan', shortName: 'KAZ', countryCode: '+7' },
  { id: 'KE', name: 'Kenya', shortName: 'KEN', countryCode: '+254' },
  { id: 'KI', name: 'Kiribati', shortName: 'KIR', countryCode: '+686' },
  { id: 'KW', name: 'Kuwait', shortName: 'KWT', countryCode: '+965' },
  { id: 'KG', name: 'Kyrgyzstan', shortName: 'KGZ', countryCode: '+996' },
  { id: 'LA', name: 'Laos', shortName: 'LAO', countryCode: '+856' },
  { id: 'LV', name: 'Latvia', shortName: 'LVA', countryCode: '+371' },
  { id: 'LB', name: 'Lebanon', shortName: 'LBN', countryCode: '+961' },
  { id: 'LS', name: 'Lesotho', shortName: 'LSO', countryCode: '+266' },
  { id: 'LR', name: 'Liberia', shortName: 'LBR', countryCode: '+231' },
  { id: 'LY', name: 'Libya', shortName: 'LBY', countryCode: '+218' },
  { id: 'LI', name: 'Liechtenstein', shortName: 'LIE', countryCode: '+423' },
  { id: 'LT', name: 'Lithuania', shortName: 'LTU', countryCode: '+370' },
  { id: 'LU', name: 'Luxembourg', shortName: 'LUX', countryCode: '+352' },
  { id: 'MG', name: 'Madagascar', shortName: 'MDG', countryCode: '+261' },
  { id: 'MW', name: 'Malawi', shortName: 'MWI', countryCode: '+265' },
  { id: 'MY', name: 'Malaysia', shortName: 'MYS', countryCode: '+60' },
  { id: 'MV', name: 'Maldives', shortName: 'MDV', countryCode: '+960' },
  { id: 'ML', name: 'Mali', shortName: 'MLI', countryCode: '+223' },
  { id: 'MT', name: 'Malta', shortName: 'MLT', countryCode: '+356' },
  { id: 'MH', name: 'Marshall Islands', shortName: 'MHL', countryCode: '+692' },
  { id: 'MR', name: 'Mauritania', shortName: 'MRT', countryCode: '+222' },
  { id: 'MU', name: 'Mauritius', shortName: 'MUS', countryCode: '+230' },
  { id: 'MX', name: 'Mexico', shortName: 'MEX', countryCode: '+52' },
  { id: 'FM', name: 'Micronesia', shortName: 'FSM', countryCode: '+691' },
  { id: 'MD', name: 'Moldova', shortName: 'MDA', countryCode: '+373' },
  { id: 'MC', name: 'Monaco', shortName: 'MCO', countryCode: '+377' },
  { id: 'MN', name: 'Mongolia', shortName: 'MNG', countryCode: '+976' },
  { id: 'ME', name: 'Montenegro', shortName: 'MNE', countryCode: '+382' },
  { id: 'MS', name: 'Montserrat', shortName: 'MSR', countryCode: '+1-664' },
  { id: 'MA', name: 'Morocco', shortName: 'MAR', countryCode: '+212' },
  { id: 'MZ', name: 'Mozambique', shortName: 'MOZ', countryCode: '+258' },
  { id: 'MM', name: 'Myanmar', shortName: 'MMR', countryCode: '+95' },
  { id: 'NA', name: 'Namibia', shortName: 'NAM', countryCode: '+264' },
  { id: 'NR', name: 'Nauru', shortName: 'NRU', countryCode: '+674' },
  { id: 'NP', name: 'Nepal', shortName: 'NPL', countryCode: '+977' },
  { id: 'NL', name: 'Netherlands', shortName: 'NLD', countryCode: '+31' },
  { id: 'NC', name: 'New Caledonia', shortName: 'NCL', countryCode: '+687' },
  { id: 'NZ', name: 'New Zealand', shortName: 'NZL', countryCode: '+64' },
  { id: 'NI', name: 'Nicaragua', shortName: 'NIC', countryCode: '+505' },
  { id: 'NE', name: 'Niger', shortName: 'NER', countryCode: '+227' },
  { id: 'NG', name: 'Nigeria', shortName: 'NGA', countryCode: '+234' },
  { id: 'NU', name: 'Niue', shortName: 'NIU', countryCode: '+683' },
  { id: 'NF', name: 'Norfolk Island', shortName: 'NFK', countryCode: '+672' },
  { id: 'MK', name: 'North Macedonia', shortName: 'MKD', countryCode: '+389' },
  {
    id: 'MP',
    name: 'Northern Mariana Islands',
    shortName: 'MNP',
    countryCode: '+1-670',
  },
  { id: 'NO', name: 'Norway', shortName: 'NOR', countryCode: '+47' },
  { id: 'OM', name: 'Oman', shortName: 'OMN', countryCode: '+968' },
  { id: 'PK', name: 'Pakistan', shortName: 'PAK', countryCode: '+92' },
  { id: 'PW', name: 'Palau', shortName: 'PLW', countryCode: '+680' },
  { id: 'PS', name: 'Palestine', shortName: 'PSE', countryCode: '+970' },
  { id: 'PA', name: 'Panama', shortName: 'PAN', countryCode: '+507' },
  { id: 'PG', name: 'Papua New Guinea', shortName: 'PNG', countryCode: '+675' },
  { id: 'PY', name: 'Paraguay', shortName: 'PRY', countryCode: '+595' },
  { id: 'PE', name: 'Peru', shortName: 'PER', countryCode: '+51' },
  { id: 'PH', name: 'Philippines', shortName: 'PHL', countryCode: '+63' },
  { id: 'PN', name: 'Pitcairn Islands', shortName: 'PCN', countryCode: '+64' },
  { id: 'PL', name: 'Poland', shortName: 'POL', countryCode: '+48' },
  { id: 'PT', name: 'Portugal', shortName: 'PRT', countryCode: '+351' },
  {
    id: 'PR',
    name: 'Puerto Rico',
    shortName: 'PRI',
    countryCode: '+1-787, +1-939',
  },
  { id: 'QA', name: 'Qatar', shortName: 'QAT', countryCode: '+974' },
  { id: 'RE', name: 'Réunion', shortName: 'REU', countryCode: '+262' },
  { id: 'RO', name: 'Romania', shortName: 'ROU', countryCode: '+40' },
  { id: 'RU', name: 'Russia', shortName: 'RUS', countryCode: '+7' },
  { id: 'RW', name: 'Rwanda', shortName: 'RWA', countryCode: '+250' },
  { id: 'BL', name: 'Saint Barthélemy', shortName: 'BLM', countryCode: '+590' },
  { id: 'SH', name: 'Saint Helena', shortName: 'SHN', countryCode: '+290' },
  {
    id: 'KN',
    name: 'Saint Kitts and Nevis',
    shortName: 'KNA',
    countryCode: '+1-869',
  },
  { id: 'LC', name: 'Saint Lucia', shortName: 'LCA', countryCode: '+1-758' },
  { id: 'MF', name: 'Saint Martin', shortName: 'MAF', countryCode: '+590' },
  {
    id: 'PM',
    name: 'Saint Pierre and Miquelon',
    shortName: 'SPM',
    countryCode: '+508',
  },
  {
    id: 'VC',
    name: 'Saint Vincent and the Grenadines',
    shortName: 'VCT',
    countryCode: '+1-784',
  },
  { id: 'WS', name: 'Samoa', shortName: 'WSM', countryCode: '+685' },
  { id: 'SM', name: 'San Marino', shortName: 'SMR', countryCode: '+378' },
  {
    id: 'ST',
    name: 'São Tomé and Príncipe',
    shortName: 'STP',
    countryCode: '+239',
  },
  { id: 'SA', name: 'Saudi Arabia', shortName: 'SAU', countryCode: '+966' },
  { id: 'SN', name: 'Senegal', shortName: 'SEN', countryCode: '+221' },
  { id: 'RS', name: 'Serbia', shortName: 'SRB', countryCode: '+381' },
  { id: 'SC', name: 'Seychelles', shortName: 'SYC', countryCode: '+248' },
  { id: 'SL', name: 'Sierra Leone', shortName: 'SLE', countryCode: '+232' },
  { id: 'SG', name: 'Singapore', shortName: 'SGP', countryCode: '+65' },
  { id: 'SX', name: 'Sint Maarten', shortName: 'SXM', countryCode: '+1-721' },
  { id: 'SK', name: 'Slovakia', shortName: 'SVK', countryCode: '+421' },
  { id: 'SI', name: 'Slovenia', shortName: 'SVN', countryCode: '+386' },
  { id: 'SB', name: 'Solomon Islands', shortName: 'SLB', countryCode: '+677' },
  { id: 'SO', name: 'Somalia', shortName: 'SOM', countryCode: '+252' },
  { id: 'ZA', name: 'South Africa', shortName: 'ZAF', countryCode: '+27' },
  {
    id: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    shortName: 'SGS',
    countryCode: '+500',
  },
  { id: 'SS', name: 'South Sudan', shortName: 'SSD', countryCode: '+211' },
  { id: 'ES', name: 'Spain', shortName: 'ESP', countryCode: '+34' },
  { id: 'LK', name: 'Sri Lanka', shortName: 'LKA', countryCode: '+94' },
  { id: 'SD', name: 'Sudan', shortName: 'SDN', countryCode: '+249' },
  { id: 'SR', name: 'Suriname', shortName: 'SUR', countryCode: '+597' },
  {
    id: 'SJ',
    name: 'Svalbard and Jan Mayen',
    shortName: 'SJM',
    countryCode: '+47',
  },
  { id: 'SE', name: 'Sweden', shortName: 'SWE', countryCode: '+46' },
  { id: 'CH', name: 'Switzerland', shortName: 'CHE', countryCode: '+41' },
  { id: 'SY', name: 'Syria', shortName: 'SYR', countryCode: '+963' },
  { id: 'TW', name: 'Taiwan', shortName: 'TWN', countryCode: '+886' },
  { id: 'TJ', name: 'Tajikistan', shortName: 'TJK', countryCode: '+992' },
  { id: 'TZ', name: 'Tanzania', shortName: 'TZA', countryCode: '+255' },
  { id: 'TH', name: 'Thailand', shortName: 'THA', countryCode: '+66' },
  { id: 'TG', name: 'Togo', shortName: 'TGO', countryCode: '+228' },
  { id: 'TK', name: 'Tokelau', shortName: 'TKL', countryCode: '+690' },
  { id: 'TO', name: 'Tonga', shortName: 'TON', countryCode: '+676' },
  {
    id: 'TT',
    name: 'Trinidad and Tobago',
    shortName: 'TTO',
    countryCode: '+1-868',
  },
  { id: 'TN', name: 'Tunisia', shortName: 'TUN', countryCode: '+216' },
  { id: 'TR', name: 'Turkey', shortName: 'TUR', countryCode: '+90' },
  { id: 'TM', name: 'Turkmenistan', shortName: 'TKM', countryCode: '+993' },
  {
    id: 'TC',
    name: 'Turks and Caicos Islands',
    shortName: 'TCA',
    countryCode: '+1-649',
  },
  { id: 'TV', name: 'Tuvalu', shortName: 'TUV', countryCode: '+688' },
  { id: 'UG', name: 'Uganda', shortName: 'UGA', countryCode: '+256' },
  { id: 'UA', name: 'Ukraine', shortName: 'UKR', countryCode: '+380' },
  {
    id: 'AE',
    name: 'United Arab Emirates',
    shortName: 'ARE',
    countryCode: '+971',
  },
  { id: 'GB', name: 'United Kingdom', shortName: 'GBR', countryCode: '+44' },
  { id: 'US', name: 'United States', shortName: 'USA', countryCode: '+1' },
  { id: 'UY', name: 'Uruguay', shortName: 'URY', countryCode: '+598' },
  { id: 'UZ', name: 'Uzbekistan', shortName: 'UZB', countryCode: '+998' },
  { id: 'VU', name: 'Vanuatu', shortName: 'VUT', countryCode: '+678' },
  { id: 'VA', name: 'Vatican City', shortName: 'VAT', countryCode: '+379' },
  { id: 'VE', name: 'Venezuela', shortName: 'VEN', countryCode: '+58' },
  { id: 'VN', name: 'Vietnam', shortName: 'VNM', countryCode: '+84' },
  {
    id: 'VG',
    name: 'British Virgin Islands',
    shortName: 'VGB',
    countryCode: '+1-284',
  },
  {
    id: 'VI',
    name: 'U.S. Virgin Islands',
    shortName: 'VIR',
    countryCode: '+1-340',
  },
  {
    id: 'WF',
    name: 'Wallis and Futuna',
    shortName: 'WLF',
    countryCode: '+681',
  },
  { id: 'EH', name: 'Western Sahara', shortName: 'ESH', countryCode: '+212' },
  { id: 'YE', name: 'Yemen', shortName: 'YEM', countryCode: '+967' },
  { id: 'ZM', name: 'Zambia', shortName: 'ZMB', countryCode: '+260' },
  { id: 'ZW', name: 'Zimbabwe', shortName: 'ZWE', countryCode: '+263' },
];
