import { Currency } from '../entities';

export const currencySeedData: Array<Currency> = [
  {
    id: 'AED',
    code: 'AED',
    symbol: 'د.إ',
    countryCode: 'AE',
    name: 'UAE Dirham',
    countryName: 'United Arab Emirates',
  },
  {
    id: 'AFN',
    code: 'AFN',
    symbol: '؋',
    name: 'Afghani',
    countryCode: 'AF',
    countryName: 'Afghanistan',
  },
  {
    id: 'ALL',
    code: 'ALL',
    symbol: 'L',
    name: 'Lek',
    countryCode: 'AL',
    countryName: 'Albania',
  },
  {
    id: 'AMD',
    code: 'AMD',
    symbol: '֏',
    countryCode: 'AM',
    name: 'Armenian Dram',
    countryName: 'Armenia',
  },
  {
    id: 'AOA',
    code: 'AOA',
    symbol: 'Kz',
    name: 'Kwanza',
    countryCode: 'AO',
    countryName: 'Angola',
  },
  {
    id: 'ARS',
    code: 'ARS',
    symbol: '$',
    countryCode: 'AR',
    name: 'Argentine Peso',
    countryName: 'Argentina',
  },
  {
    id: 'AUD',
    code: 'AUD',
    symbol: 'A$',
    countryCode: 'AU',
    countryName: 'Australia',
    name: 'Australian Dollar',
  },
  {
    id: 'AWG',
    code: 'AWG',
    symbol: 'ƒ',
    countryCode: 'AW',
    countryName: 'Aruba',
    name: 'Aruban Florin',
  },
  {
    id: 'AZN',
    code: 'AZN',
    symbol: '₼',
    countryCode: 'AZ',
    countryName: 'Azerbaijan',
    name: 'Azerbaijani Manat',
  },
  {
    id: 'BAM',
    code: 'BAM',
    symbol: 'KM',
    countryCode: 'BA',
    name: 'Convertible Mark',
    countryName: 'Bosnia & Herzegovina',
  },
  {
    id: 'BBD',
    code: 'BBD',
    symbol: '$',
    countryCode: 'BB',
    countryName: 'Barbados',
    name: 'Barbadian Dollar',
  },
  {
    id: 'BDT',
    code: 'BDT',
    symbol: '৳',
    name: 'Taka',
    countryCode: 'BD',
    countryName: 'Bangladesh',
  },
  {
    id: 'BGN',
    code: 'BGN',
    symbol: 'лв',
    name: 'Lev',
    countryCode: 'BG',
    countryName: 'Bulgaria',
  },
  {
    id: 'BHD',
    code: 'BHD',
    symbol: '.د.ب',
    countryCode: 'BH',
    countryName: 'Bahrain',
    name: 'Bahraini Dinar',
  },
  {
    id: 'BIF',
    code: 'BIF',
    symbol: 'FBu',
    countryCode: 'BI',
    countryName: 'Burundi',
    name: 'Burundian Franc',
  },
  {
    id: 'BMD',
    code: 'BMD',
    symbol: '$',
    countryCode: 'BM',
    countryName: 'Bermuda',
    name: 'Bermudian Dollar',
  },
  {
    id: 'BND',
    code: 'BND',
    symbol: 'B$',
    countryCode: 'BN',
    countryName: 'Brunei',
    name: 'Brunei Dollar',
  },
  {
    id: 'BOB',
    code: 'BOB',
    symbol: 'Bs',
    name: 'Boliviano',
    countryCode: 'BO',
    countryName: 'Bolivia',
  },
  {
    id: 'BRL',
    code: 'BRL',
    symbol: 'R$',
    countryCode: 'BR',
    countryName: 'Brazil',
    name: 'Brazilian Real',
  },
  {
    id: 'BSD',
    code: 'BSD',
    symbol: '$',
    countryCode: 'BS',
    countryName: 'Bahamas',
    name: 'Bahamian Dollar',
  },
  {
    id: 'BTN',
    code: 'BTN',
    symbol: 'Nu.',
    name: 'Ngultrum',
    countryCode: 'BT',
    countryName: 'Bhutan',
  },
  {
    id: 'BWP',
    code: 'BWP',
    symbol: 'P',
    name: 'Pula',
    countryCode: 'BW',
    countryName: 'Botswana',
  },
  {
    id: 'BYN',
    code: 'BYN',
    symbol: 'Br',
    countryCode: 'BY',
    countryName: 'Belarus',
    name: 'Belarusian Ruble',
  },
  {
    id: 'BZD',
    code: 'BZD',
    symbol: 'BZ$',
    countryCode: 'BZ',
    countryName: 'Belize',
    name: 'Belize Dollar',
  },
  {
    id: 'CAD',
    code: 'CAD',
    symbol: 'CA$',
    countryCode: 'CA',
    countryName: 'Canada',
    name: 'Canadian Dollar',
  },
  {
    id: 'CDF',
    code: 'CDF',
    symbol: 'FC',
    countryCode: 'CD',
    name: 'Congolese Franc',
    countryName: 'Democratic Republic of the Congo',
  },
  {
    id: 'CHF',
    code: 'CHF',
    symbol: 'CHF',
    countryCode: 'CH',
    name: 'Swiss Franc',
    countryName: 'Switzerland',
  },
  {
    id: 'CLP',
    code: 'CLP',
    symbol: 'CLP$',
    countryCode: 'CL',
    countryName: 'Chile',
    name: 'Chilean Peso',
  },
  {
    id: 'CNY',
    code: 'CNY',
    symbol: '¥',
    countryCode: 'CN',
    countryName: 'China',
    name: 'Chinese Yuan',
  },
  {
    id: 'COP',
    code: 'COP',
    symbol: 'COL$',
    countryCode: 'CO',
    countryName: 'Colombia',
    name: 'Colombian Peso',
  },
  {
    id: 'CRC',
    code: 'CRC',
    symbol: '₡',
    countryCode: 'CR',
    countryName: 'Costa Rica',
    name: 'Costa Rican Colón',
  },
  {
    id: 'CUP',
    code: 'CUP',
    symbol: '₱',
    countryCode: 'CU',
    countryName: 'Cuba',
    name: 'Cuban Peso',
  },
  {
    id: 'CVE',
    code: 'CVE',
    symbol: '$',
    countryCode: 'CV',
    countryName: 'Cape Verde',
    name: 'Cape Verde Escudo',
  },
  {
    id: 'CZK',
    code: 'CZK',
    symbol: 'Kč',
    countryCode: 'CZ',
    name: 'Czech Koruna',
    countryName: 'Czech Republic',
  },
  {
    id: 'DJF',
    code: 'DJF',
    symbol: 'Fdj',
    countryCode: 'DJ',
    name: 'Djibouti Franc',
    countryName: 'Djibouti',
  },
  {
    id: 'DKK',
    code: 'DKK',
    symbol: 'kr',
    countryCode: 'DK',
    name: 'Danish Krone',
    countryName: 'Denmark',
  },
  {
    id: 'DOP',
    code: 'DOP',
    symbol: 'RD$',
    countryCode: 'DO',
    name: 'Dominican Peso',
    countryName: 'Dominican Republic',
  },
  {
    id: 'DZD',
    code: 'DZD',
    symbol: 'دج',
    countryCode: 'DZ',
    countryName: 'Algeria',
    name: 'Algerian Dinar',
  },
  {
    id: 'EGP',
    code: 'EGP',
    symbol: '£',
    countryCode: 'EG',
    countryName: 'Egypt',
    name: 'Egyptian Pound',
  },
  {
    id: 'ETB',
    code: 'ETB',
    symbol: 'Br',
    countryCode: 'ET',
    name: 'Ethiopian Birr',
    countryName: 'Ethiopia',
  },
  {
    id: 'EUR',
    code: 'EUR',
    symbol: '€',
    name: 'Euro',
    countryCode: 'EU',
    countryName: 'European Union',
  },
  {
    id: 'FJD',
    code: 'FJD',
    symbol: 'FJ$',
    countryCode: 'FJ',
    countryName: 'Fiji',
    name: 'Fijian Dollar',
  },
  {
    id: 'GBP',
    code: 'GBP',
    symbol: '£',
    countryCode: 'GB',
    countryName: 'United Kingdom',
    name: 'British Pound Sterling',
  },
  {
    id: 'GEL',
    code: 'GEL',
    symbol: '₾',
    name: 'Lari',
    countryCode: 'GE',
    countryName: 'Georgia',
  },
  {
    id: 'GHS',
    code: 'GHS',
    symbol: 'GH₵',
    countryCode: 'GH',
    countryName: 'Ghana',
    name: 'Ghanaian Cedi',
  },
  {
    id: 'GMD',
    code: 'GMD',
    symbol: 'D',
    name: 'Dalasi',
    countryCode: 'GM',
    countryName: 'Gambia',
  },
  {
    id: 'GNF',
    code: 'GNF',
    symbol: 'FG',
    countryCode: 'GN',
    countryName: 'Guinea',
    name: 'Guinean Franc',
  },
  {
    id: 'GTQ',
    code: 'GTQ',
    symbol: 'Q',
    name: 'Quetzal',
    countryCode: 'GT',
    countryName: 'Guatemala',
  },
  {
    id: 'GYD',
    code: 'GYD',
    symbol: '$',
    countryCode: 'GY',
    countryName: 'Guyana',
    name: 'Guyanese Dollar',
  },
  {
    id: 'HKD',
    code: 'HKD',
    symbol: 'HK$',
    countryCode: 'HK',
    countryName: 'Hong Kong',
    name: 'Hong Kong Dollar',
  },
  {
    id: 'HNL',
    code: 'HNL',
    symbol: 'L',
    name: 'Lempira',
    countryCode: 'HN',
    countryName: 'Honduras',
  },
  {
    id: 'HRK',
    code: 'HRK',
    symbol: 'kn',
    name: 'Kuna',
    countryCode: 'HR',
    countryName: 'Croatia',
  },
  {
    id: 'HTG',
    code: 'HTG',
    symbol: 'G',
    name: 'Gourde',
    countryCode: 'HT',
    countryName: 'Haiti',
  },
  {
    id: 'HUF',
    code: 'HUF',
    symbol: 'Ft',
    name: 'Forint',
    countryCode: 'HU',
    countryName: 'Hungary',
  },
  {
    id: 'IDR',
    code: 'IDR',
    symbol: 'Rp',
    name: 'Rupiah',
    countryCode: 'ID',
    countryName: 'Indonesia',
  },
  {
    id: 'ILS',
    code: 'ILS',
    symbol: '₪',
    countryCode: 'IL',
    countryName: 'Israel',
    name: 'Israeli New Shekel',
  },
  {
    id: 'INR',
    code: 'INR',
    symbol: '₹',
    countryCode: 'IN',
    countryName: 'India',
    name: 'Indian Rupee',
  },
  {
    id: 'IQD',
    code: 'IQD',
    symbol: 'ع.د',
    countryCode: 'IQ',
    countryName: 'Iraq',
    name: 'Iraqi Dinar',
  },
  {
    id: 'IRR',
    code: 'IRR',
    symbol: '﷼',
    countryCode: 'IR',
    countryName: 'Iran',
    name: 'Iranian Rial',
  },
  {
    id: 'ISK',
    code: 'ISK',
    symbol: 'kr',
    countryCode: 'IS',
    countryName: 'Iceland',
    name: 'Iceland Krona',
  },
  {
    id: 'JMD',
    code: 'JMD',
    symbol: 'J$',
    countryCode: 'JM',
    countryName: 'Jamaica',
    name: 'Jamaican Dollar',
  },
  {
    id: 'JPY',
    code: 'JPY',
    symbol: '¥',
    name: 'Yen',
    countryCode: 'JP',
    countryName: 'Japan',
  },
  {
    id: 'KES',
    code: 'KES',
    symbol: 'KSh',
    countryCode: 'KE',
    countryName: 'Kenya',
    name: 'Kenyan Shilling',
  },
  {
    id: 'KGS',
    code: 'KGS',
    symbol: 'лв',
    name: 'Som',
    countryCode: 'KG',
    countryName: 'Kyrgyzstan',
  },
  {
    id: 'KHR',
    code: 'KHR',
    symbol: '៛',
    name: 'Riel',
    countryCode: 'KH',
    countryName: 'Cambodia',
  },
  {
    id: 'KMF',
    code: 'KMF',
    symbol: 'CF',
    countryCode: 'KM',
    countryName: 'Comoros',
    name: 'Comorian Franc',
  },
  {
    id: 'KRW',
    code: 'KRW',
    symbol: '₩',
    name: 'Won',
    countryCode: 'KR',
    countryName: 'South Korea',
  },
  {
    id: 'KWD',
    code: 'KWD',
    symbol: 'د.ك',
    countryCode: 'KW',
    countryName: 'Kuwait',
    name: 'Kuwaiti Dinar',
  },
  {
    id: 'KZT',
    code: 'KZT',
    symbol: '₸',
    name: 'Tenge',
    countryCode: 'KZ',
    countryName: 'Kazakhstan',
  },
  {
    id: 'LAK',
    code: 'LAK',
    symbol: '₭',
    name: 'Kip',
    countryCode: 'LA',
    countryName: 'Laos',
  },
  {
    id: 'LBP',
    code: 'LBP',
    symbol: 'ل.ل',
    countryCode: 'LB',
    countryName: 'Lebanon',
    name: 'Lebanese Pound',
  },
  {
    id: 'LKR',
    code: 'LKR',
    symbol: 'Rs',
    countryCode: 'LK',
    countryName: 'Sri Lanka',
    name: 'Sri Lankan Rupee',
  },
  {
    id: 'LRD',
    code: 'LRD',
    symbol: 'L$',
    countryCode: 'LR',
    countryName: 'Liberia',
    name: 'Liberian Dollar',
  },
  {
    id: 'LSL',
    code: 'LSL',
    symbol: 'L',
    name: 'Loti',
    countryCode: 'LS',
    countryName: 'Lesotho',
  },
  {
    id: 'LYD',
    code: 'LYD',
    symbol: 'ل.د',
    countryCode: 'LY',
    countryName: 'Libya',
    name: 'Libyan Dinar',
  },
  {
    id: 'MAD',
    code: 'MAD',
    symbol: 'د.م.',
    countryCode: 'MA',
    countryName: 'Morocco',
    name: 'Moroccan Dirham',
  },
  {
    id: 'MDL',
    code: 'MDL',
    symbol: 'L',
    countryCode: 'MD',
    name: 'Moldovan Leu',
    countryName: 'Moldova',
  },
  {
    id: 'MGA',
    code: 'MGA',
    symbol: 'Ar',
    countryCode: 'MG',
    name: 'Malagasy Ariary',
    countryName: 'Madagascar',
  },
  {
    id: 'MKD',
    code: 'MKD',
    symbol: 'ден',
    name: 'Denar',
    countryCode: 'MK',
    countryName: 'North Macedonia',
  },
  {
    id: 'MMK',
    code: 'MMK',
    symbol: 'K',
    name: 'Kyat',
    countryCode: 'MM',
    countryName: 'Myanmar',
  },
  {
    id: 'MNT',
    code: 'MNT',
    symbol: '₮',
    name: 'Tugrik',
    countryCode: 'MN',
    countryName: 'Mongolia',
  },
  {
    id: 'MOP',
    code: 'MOP',
    symbol: 'MOP$',
    name: 'Pataca',
    countryCode: 'MO',
    countryName: 'Macau',
  },
  {
    id: 'MRU',
    code: 'MRU',
    symbol: 'UM',
    name: 'Ouguiya',
    countryCode: 'MR',
    countryName: 'Mauritania',
  },
  {
    id: 'MUR',
    code: 'MUR',
    symbol: '₨',
    countryCode: 'MU',
    name: 'Mauritian Rupee',
    countryName: 'Mauritius',
  },
  {
    id: 'MVR',
    code: 'MVR',
    symbol: 'Rf',
    name: 'Rufiyaa',
    countryCode: 'MV',
    countryName: 'Maldives',
  },
  {
    id: 'MWK',
    code: 'MWK',
    symbol: 'MK',
    name: 'Kwacha',
    countryCode: 'MW',
    countryName: 'Malawi',
  },
  {
    id: 'MXN',
    code: 'MXN',
    symbol: 'MX$',
    countryCode: 'MX',
    name: 'Mexican Peso',
    countryName: 'Mexico',
  },
  {
    id: 'MYR',
    code: 'MYR',
    symbol: 'RM',
    name: 'Ringgit',
    countryCode: 'MY',
    countryName: 'Malaysia',
  },
  {
    id: 'MZN',
    code: 'MZN',
    symbol: 'MT',
    name: 'Metical',
    countryCode: 'MZ',
    countryName: 'Mozambique',
  },
  {
    id: 'NAD',
    code: 'NAD',
    symbol: 'N$',
    countryCode: 'NA',
    countryName: 'Namibia',
    name: 'Namibian Dollar',
  },
  {
    id: 'NGN',
    code: 'NGN',
    symbol: '₦',
    countryCode: 'NG',
    countryName: 'Nigeria',
    name: 'Nigerian Naira',
  },
  {
    id: 'NIO',
    code: 'NIO',
    symbol: 'C$',
    countryCode: 'NI',
    name: 'Córdoba Oro',
    countryName: 'Nicaragua',
  },
  {
    id: 'NOK',
    code: 'NOK',
    symbol: 'kr',
    countryCode: 'NO',
    countryName: 'Norway',
    name: 'Norwegian Krone',
  },
  {
    id: 'NPR',
    code: 'NPR',
    symbol: '₨',
    countryCode: 'NP',
    countryName: 'Nepal',
    name: 'Nepalese Rupee',
  },
  {
    id: 'NZD',
    code: 'NZD',
    symbol: 'NZ$',
    countryCode: 'NZ',
    countryName: 'New Zealand',
    name: 'New Zealand Dollar',
  },
  {
    id: 'OMR',
    code: 'OMR',
    symbol: 'ر.ع.',
    countryCode: 'OM',
    name: 'Omani Rial',
    countryName: 'Oman',
  },
  {
    id: 'PAB',
    code: 'PAB',
    symbol: 'B/.',
    name: 'Balboa',
    countryCode: 'PA',
    countryName: 'Panama',
  },
  {
    id: 'PEN',
    code: 'PEN',
    symbol: 'S/.',
    countryCode: 'PE',
    name: 'Nuevo Sol',
    countryName: 'Peru',
  },
  {
    id: 'PGK',
    code: 'PGK',
    symbol: 'K',
    name: 'Kina',
    countryCode: 'PG',
    countryName: 'Papua New Guinea',
  },
  {
    id: 'PHP',
    code: 'PHP',
    symbol: '₱',
    countryCode: 'PH',
    name: 'Philippine Peso',
    countryName: 'Philippines',
  },
  {
    id: 'PKR',
    code: 'PKR',
    symbol: '₨',
    countryCode: 'PK',
    countryName: 'Pakistan',
    name: 'Pakistani Rupee',
  },
  {
    id: 'PLN',
    code: 'PLN',
    symbol: 'zł',
    countryCode: 'PL',
    name: 'Polish Zloty',
    countryName: 'Poland',
  },
  {
    id: 'PYG',
    code: 'PYG',
    symbol: '₲',
    name: 'Guarani',
    countryCode: 'PY',
    countryName: 'Paraguay',
  },
  {
    id: 'QAR',
    code: 'QAR',
    symbol: '﷼',
    countryCode: 'QA',
    name: 'Qatari Rial',
    countryName: 'Qatar',
  },
  {
    id: 'RON',
    code: 'RON',
    symbol: 'lei',
    countryCode: 'RO',
    name: 'Romanian Leu',
    countryName: 'Romania',
  },
  {
    id: 'RSD',
    code: 'RSD',
    symbol: 'Дин.',
    countryCode: 'RS',
    countryName: 'Serbia',
    name: 'Serbian Dinar',
  },
  {
    id: 'RUB',
    code: 'RUB',
    symbol: '₽',
    countryCode: 'RU',
    countryName: 'Russia',
    name: 'Russian Ruble',
  },
  {
    id: 'RWF',
    code: 'RWF',
    symbol: 'FRw',
    countryCode: 'RW',
    countryName: 'Rwanda',
    name: 'Rwandan Franc',
  },
  {
    id: 'SAR',
    code: 'SAR',
    symbol: '﷼',
    countryCode: 'SA',
    name: 'Saudi Riyal',
    countryName: 'Saudi Arabia',
  },
  {
    id: 'SBD',
    code: 'SBD',
    symbol: 'SI$',
    countryCode: 'SB',
    countryName: 'Solomon Islands',
    name: 'Solomon Islands Dollar',
  },
  {
    id: 'SCR',
    code: 'SCR',
    symbol: '₨',
    countryCode: 'SC',
    countryName: 'Seychelles',
    name: 'Seychellois Rupee',
  },
  {
    id: 'SDG',
    code: 'SDG',
    symbol: 'ج.س.',
    countryCode: 'SD',
    countryName: 'Sudan',
    name: 'Sudanese Pound',
  },
  {
    id: 'SEK',
    code: 'SEK',
    symbol: 'kr',
    countryCode: 'SE',
    countryName: 'Sweden',
    name: 'Swedish Krona',
  },
  {
    id: 'SGD',
    code: 'SGD',
    symbol: 'S$',
    countryCode: 'SG',
    countryName: 'Singapore',
    name: 'Singapore Dollar',
  },
  {
    id: 'SHP',
    code: 'SHP',
    symbol: '£',
    countryCode: 'SH',
    countryName: 'Saint Helena',
    name: 'Saint Helena Pound',
  },
  {
    id: 'SLL',
    code: 'SLL',
    symbol: 'Le',
    countryCode: 'SL',
    countryName: 'Sierra Leone',
    name: 'Leone',
  },
  {
    id: 'SOS',
    code: 'SOS',
    symbol: 'S',
    countryCode: 'SO',
    countryName: 'Somalia',
    name: 'Somali Shilling',
  },
  {
    id: 'SRD',
    code: 'SRD',
    symbol: '$',
    countryCode: 'SR',
    countryName: 'Suriname',
    name: 'Surinamese Dollar',
  },
  {
    id: 'SSP',
    code: 'SSP',
    symbol: '£',
    countryCode: 'SS',
    countryName: 'South Sudan',
    name: 'South Sudanese Pound',
  },
  {
    id: 'STN',
    code: 'STN',
    symbol: 'Db',
    name: 'Dobra',
    countryCode: 'ST',
    countryName: 'São Tomé & Príncipe',
  },
  {
    id: 'SVC',
    code: 'SVC',
    symbol: '₡',
    countryCode: 'SV',
    name: 'El Salvador Colón',
    countryName: 'El Salvador',
  },
  {
    id: 'SYP',
    code: 'SYP',
    symbol: '£',
    countryCode: 'SY',
    countryName: 'Syria',
    name: 'Syrian Pound',
  },
  {
    id: 'SZL',
    code: 'SZL',
    symbol: 'E',
    name: 'Lilangeni',
    countryCode: 'SZ',
    countryName: 'Eswatini',
  },
  {
    id: 'THB',
    code: 'THB',
    symbol: '฿',
    name: 'Baht',
    countryCode: 'TH',
    countryName: 'Thailand',
  },
  {
    id: 'TJS',
    code: 'TJS',
    symbol: 'ЅМ',
    name: 'Somoni',
    countryCode: 'TJ',
    countryName: 'Tajikistan',
  },
  {
    id: 'TMT',
    code: 'TMT',
    symbol: 'm',
    countryCode: 'TM',
    countryName: 'Turkmenistan',
    name: 'Turkmenistan Manat',
  },
  {
    id: 'TND',
    code: 'TND',
    symbol: 'د.ت',
    countryCode: 'TN',
    countryName: 'Tunisia',
    name: 'Tunisian Dinar',
  },
  {
    id: 'TOP',
    code: 'TOP',
    symbol: 'T$',
    name: 'Paʻanga',
    countryCode: 'TO',
    countryName: 'Tonga',
  },
  {
    id: 'TRY',
    code: 'TRY',
    symbol: '₺',
    countryCode: 'TR',
    countryName: 'Turkey',
    name: 'Turkish Lira',
  },
  {
    id: 'TTD',
    code: 'TTD',
    symbol: 'TT$',
    countryCode: 'TT',
    countryName: 'Trinidad & Tobago',
    name: 'Trinidad & Tobago Dollar',
  },
  {
    id: 'TWD',
    code: 'TWD',
    symbol: 'NT$',
    countryCode: 'TW',
    countryName: 'Taiwan',
    name: 'New Taiwan Dollar',
  },
  {
    id: 'TZS',
    code: 'TZS',
    symbol: 'TSh',
    countryCode: 'TZ',
    countryName: 'Tanzania',
    name: 'Tanzanian Shilling',
  },
  {
    id: 'UAH',
    code: 'UAH',
    symbol: '₴',
    name: 'Hryvnia',
    countryCode: 'UA',
    countryName: 'Ukraine',
  },
  {
    id: 'UGX',
    code: 'UGX',
    symbol: 'USh',
    countryCode: 'UG',
    countryName: 'Uganda',
    name: 'Ugandan Shilling',
  },
  {
    id: 'USD',
    code: 'USD',
    symbol: '$',
    countryCode: 'US',
    name: 'US Dollar',
    countryName: 'United States',
  },
  {
    id: 'UYU',
    code: 'UYU',
    symbol: '$U',
    countryCode: 'UY',
    countryName: 'Uruguay',
    name: 'Uruguayan Peso',
  },
  {
    id: 'UZS',
    code: 'UZS',
    symbol: 'сўм',
    countryCode: 'UZ',
    name: 'Uzbekistani Som',
    countryName: 'Uzbekistan',
  },
  {
    id: 'VES',
    code: 'VES',
    symbol: 'Bs S',
    countryCode: 'VE',
    countryName: 'Venezuela',
    name: 'Venezuelan Bolívar',
  },
  {
    id: 'VND',
    code: 'VND',
    symbol: '₫',
    countryCode: 'VN',
    countryName: 'Vietnam',
    name: 'Vietnamese Dong',
  },
  {
    id: 'VUV',
    code: 'VUV',
    name: 'Vatu',
    symbol: 'VT',
    countryCode: 'VU',
    countryName: 'Vanuatu',
  },
  {
    id: 'WST',
    code: 'WST',
    name: 'Tala',
    symbol: 'WS$',
    countryCode: 'WS',
    countryName: 'Samoa',
  },
  {
    id: 'XAF',
    code: 'XAF',
    symbol: 'FCFA',
    countryCode: 'CM',
    name: 'CFA Franc BEAC',
    countryName: 'Central African States (multiple)',
  },
  {
    id: 'XCD',
    code: 'XCD',
    symbol: '$',
    countryCode: 'AG',
    name: 'East Caribbean Dollar',
    countryName: 'Eastern Caribbean States',
  },
  {
    id: 'XOF',
    code: 'XOF',
    symbol: 'CFA',
    countryCode: 'BJ',
    name: 'CFA Franc BCEAO',
    countryName: 'Western African States',
  },
  {
    id: 'XPF',
    code: 'XPF',
    symbol: '₣',
    countryCode: 'PF',
    name: 'CFP Franc',
    countryName: 'French Pacific Territories',
  },
  {
    id: 'YER',
    code: 'YER',
    symbol: '﷼',
    countryCode: 'YE',
    name: 'Yemeni Rial',
    countryName: 'Yemen',
  },
  {
    id: 'ZAR',
    code: 'ZAR',
    symbol: 'R',
    countryCode: 'ZA',
    name: 'Rand',
    countryName: 'South Africa',
  },
  {
    id: 'ZMW',
    code: 'ZMW',
    symbol: 'K',
    countryCode: 'ZM',
    countryName: 'Zambia',
    name: 'Zambian Kwacha',
  },
];
